version: '2.0'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind 0.0.0.0:8000 -w 4 oct2py_server.wsgi
    volumes:
      - ./oct2py_server:/oct2py_server
    environment:
      CELERY_BROKER_URL: "amqp://rabbitmq:rabbitmq@rabbit:5672/"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    ports:
      - "8000:8000"
    depends_on:
      - rabbit
      - redis

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
  
  redis:
    image: "redis:3.2.0"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"

  worker:
    build: .
    command: celery -A oct2py_server worker -l info
    volumes:
      - ./oct2py_server:/oct2py_server
    environment:
      CELERY_BROKER_URL: "amqp://rabbitmq:rabbitmq@rabbit:5672/"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - web
      - rabbit
      - redis
  
  # nginx:
  #   image: nginx:latest
  #   ports:
  #   - "80:80"
  #   volumes:
  #     - ./oct2py_server:/oct2py_server
  #     - ./front-end/octave-front/build:/var/www
  #     - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - web


volumes:
  redisdata:
