# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OctaveCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('upload', models.FileField(upload_to='./api/octave_apps/')),
                ('input_number', models.IntegerField()),
            ],
        ),
    ]
