# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_octavecode_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OctaveImage',
            fields=[
                ('octavecode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.OctaveCode')),
            ],
            bases=('api.octavecode',),
        ),
    ]
