# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OctaveCode',
            new_name='ScriptCode',
        ),
    ]
