# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import scripts.models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20180325_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptcode',
            name='input_number',
            field=models.IntegerField(default=0, validators=[scripts.models.validate_positive]),
        ),
    ]
